development:
  adapter: postgresql
  database: follow_service_dev
  encoding: utf8
  host: localhost
  port: 5432
  username: Adam
test:
  adapter: postgresql
  database: follow_service_test
  encoding: utf8
  host: localhost
  port: 5432
  username: Adam